### PR TITLE
Added getCurrentOrder method and documentation

### LINKED ISSUE #99: Performance is bad when trying to save order from higher level component
The only prop that allows access to the list's order is `onChangeOrder` and calling `setState` with that really hurts the performance of the `SortableList`. If there was a method to get the current order of the list, then that could be used with a ref to the `SortableList` component and called in `onRelaseRow` to improve performance.

### PR DESCRIPTION
**Pull request by kernel-sanders**
Closes #99

### CODE REVIEW

**Comment by jcurtis** [comment]
Are you not able to use `onChangeOrder` and keep the order in state?

**Comment by jcurtis** [comment]
Ah I see you're having issue with performance using the state. If you need to keep the order but your render doesn't actually depend on it, you can keep in an instance variable instead. That way your component won't be forced to re-render.

```
class Foo extends React.Component {
  order = [];
  render() {
    return <SortableList onChangeOrder={newOrder => this.order = newOrder} />
  }
}
```

**Comment by jcurtis** [comment]
The React docs explain why it's not a good idea to use refs for this type of logic https://reactjs.org/docs/refs-and-the-dom.html

**Comment by kernel-sanders** [comment]
Using an instance variable accomplishes my needs without hurting performance and without using a ref! Thanks for the education!

**Pull request closed without merging**
